"""
Parser for ``Gemfile.lock`` (Bundler / RubyGems).

Format reference (public, reimplemented from spec):
- Plain-text file generated by ``bundle lock``.
- Top-level sections include ``GEM``, ``GIT``, ``PATH``, ``PLATFORMS``,
  ``DEPENDENCIES``, ``RUBY VERSION`` and ``BUNDLED WITH``.
- Inside ``GEM`` (and ``GIT`` / ``PATH``) blocks, lines are indented
  with two spaces and look like ``  remote: https://rubygems.org/`` and
  ``  specs:`` followed by lines like ``    rake (13.0.6)`` or
  ``    nokogiri (1.13.10)`` (with optional platform suffix
  ``-java`` / ``-x64-mingw32``).
- ``DEPENDENCIES`` block lists top-level declared gems; we use it to
  mark ``direct`` vs ``transitive``.

Implementation notes:
- We only extract the (name, version) pairs from the ``specs:`` blocks
  inside ``GEM``, ``GIT`` and ``PATH`` sections.
- A spec line looks like ``    name (version)`` or
  ``    name (version platform)``.
- Indentation is significant: spec lines have 4+ leading spaces, section
  headers have 2.
"""

from __future__ import annotations

import logging
import re
from typing import List, Set

from . import Dependency

logger = logging.getLogger("codelens.sca.gemfile_lock")


# Match `    name (1.2.3)` or `    name (1.2.3-java)` or `    name (1.2.3 x64-mingw32)`
_SPEC_RE = re.compile(r"^    ([A-Za-z0-9_.:-]+)\s+\(([^)]+)\)\s*$")
# DEPENDENCIES block: `  name` or `  name (>= 1.0)` or `  name!`
_DEP_LINE_RE = re.compile(r"^  ([A-Za-z0-9_.:-]+)(?:\s*\([^)]*\))?\s*!?\s*$")


def parse(path: str) -> List[Dependency]:
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            content = f.read()
    except Exception as exc:
        logger.warning("gemfile_lock: cannot read %s: %s", path, exc)
        return []

    # Two-pass scan: in Gemfile.lock the DEPENDENCIES block appears
    # AFTER the GEM/specs block, so we cannot know which packages are
    # direct until we have read the whole file. Pass 1 collects direct
    # names from the DEPENDENCIES block; pass 2 extracts (name, version)
    # pairs from every specs: section and tags them.

    direct_names: Set[str] = set()
    in_deps_block = False
    for raw_line in content.splitlines():
        if not raw_line.startswith((" ", "\t")):
            in_deps_block = raw_line.strip() == "DEPENDENCIES"
            continue
        if not in_deps_block:
            continue
        m = _DEP_LINE_RE.match(raw_line)
        if m:
            direct_names.add(m.group(1).lower())

    deps: List[Dependency] = []
    seen: Set[str] = set()
    in_specs = False

    for raw_line in content.splitlines():
        # Top-level section headers toggle the specs state.
        if not raw_line.startswith((" ", "\t")):
            in_specs = False
            continue

        stripped = raw_line.strip()
        if not stripped:
            continue

        if stripped == "specs:":
            in_specs = True
            continue
        if stripped.startswith(("remote:", "revision:", "branch:", "tag:")):
            continue

        if not in_specs:
            continue

        m = _SPEC_RE.match(raw_line)
        if not m:
            continue
        name = m.group(1)
        # Version may include platform: "1.2.3", "1.2.3-java",
        # "1.2.3 x64-mingw32" — take the bare version (everything up
        # to first whitespace or dash-after-digits).
        version_field = m.group(2).strip()
        bare = re.split(r"[\s-]", version_field, maxsplit=1)[0]
        if not name or not bare:
            continue
        key = (name.lower(), bare)
        if key in seen:
            continue
        seen.add(key)
        deps.append(
            Dependency(
                name=name,
                version=bare,
                ecosystem="gem",
                source_file=path,
                transitivity="direct" if name.lower() in direct_names else "transitive",
            )
        )

    return deps


__all__ = ["parse"]
